apiVersion: v1
kind: Secret
metadata:
  name: kyma-cap-s4ems-connectivity-secret
type: opaque
data:
  .metadata:
   eyJjcmVkZW50aWFsUHJvcGVydGllcyI6W3sibmFtZSI6InN1YmFjY291bnRfc3ViZG9tYWluIiwiZm9ybWF0IjoidGV4dCJ9LHsibmFtZSI6InRva2VuX3NlcnZpY2VfZG9tYWluIiwiZm9ybWF0IjoidGV4dCJ9LHsibmFtZSI6ImNyZWRlbnRpYWwtdHlwZSIsImZvcm1hdCI6InRleHQifSx7Im5hbWUiOiJjbGllbnRzZWNyZXQiLCJmb3JtYXQiOiJ0ZXh0In0seyJuYW1lIjoiY29ubmVjdGl2aXR5X3NlcnZpY2UiLCJmb3JtYXQiOiJqc29uIn0seyJuYW1lIjoic3ViYWNjb3VudF9pZCIsImZvcm1hdCI6InRleHQifSx7Im5hbWUiOiJ0b2tlbl9zZXJ2aWNlX3VybCIsImZvcm1hdCI6InRleHQifSx7Im5hbWUiOiJ0b2tlbl9zZXJ2aWNlX3VybF9wYXR0ZXJuIiwiZm9ybWF0IjoidGV4dCJ9LHsibmFtZSI6InRva2VuX3NlcnZpY2VfdXJsX3BhdHRlcm5fdGVuYW50X2tleSIsImZvcm1hdCI6InRleHQifSx7Im5hbWUiOiJ4c2FwcG5hbWUiLCJmb3JtYXQiOiJ0ZXh0In0seyJuYW1lIjoiY2xpZW50aWQiLCJmb3JtYXQiOiJ0ZXh0In1dLCJtZXRhRGF0YVByb3BlcnRpZXMiOlt7Im5hbWUiOiJpbnN0YW5jZV9uYW1lIiwiZm9ybWF0IjoidGV4dCJ9LHsibmFtZSI6Imluc3RhbmNlX2d1aWQiLCJmb3JtYXQiOiJ0ZXh0In0seyJuYW1lIjoicGxhbiIsImZvcm1hdCI6InRleHQifSx7Im5hbWUiOiJsYWJlbCIsImZvcm1hdCI6InRleHQifSx7Im5hbWUiOiJ0eXBlIiwiZm9ybWF0IjoidGV4dCJ9LHsibmFtZSI6InRhZ3MiLCJmb3JtYXQiOiJqc29uIn1dfQ==
  clientid:
    c2ItY2xvbmU0NjNjYThjZDM3OGY0NDNlODAzNDg0NWNhNzlhOGY4ZSFiMjI2NDk1fGNvbm5lY3Rpdml0eSFiMTc=
  clientsecret:
    MDNlZWE1MzMtMjBlZC00ZTQ0LWI4ZDUtN2Q2ODQxOGJhNzkzJE90N2VQVDhKMnFqVC1neExQeHVBMlBpWDZMMTYyei11cmJuV1pfSWpHdW89
  connectivity_service:
    eyJDQXNfcGF0aCI6Ii9hcGkvdjEvQ0FzIiwiQ0FzX3NpZ25pbmdfcGF0aCI6Ii9hcGkvdjEvQ0FzL3NpZ25pbmciLCJhcGlfcGF0aCI6Ii9hcGkvdjEiLCJ0dW5uZWxfcGF0aCI6Ii9hcGkvdjEvdHVubmVsIiwidXJsIjoiaHR0cHM6Ly9jb25uZWN0aXZpdHkuY2YuZXUxMC5oYW5hLm9uZGVtYW5kLmNvbSJ9
  credential-type: YmluZGluZy1zZWNyZXQ=
  instance_guid: NDYzY2E4Y2QtMzc4Zi00NDNlLTgwMzQtODQ1Y2E3OWE4Zjhl
  instance_name: dGVzdC1jb25uZWN0aXZpdHk=
  label: Y29ubmVjdGl2aXR5
  plan: Y29ubmVjdGl2aXR5X3Byb3h5
  subaccount_id: OWM3MWRmYjctNGFiMi00MWViLWJmMDYtYmEwNWI5MTlmYmJm
  subaccount_subdomain: ZTJldmFsaWRhdGlvbi1jMXFjZXJraA==
  tags: WyJjb25uZWN0aXZpdHkiLCJjb25uIiwiY29ubnN2YyJd
  token_service_domain: YXV0aGVudGljYXRpb24uZXUxMC5oYW5hLm9uZGVtYW5kLmNvbQ==
  token_service_url:
    aHR0cHM6Ly9lMmV2YWxpZGF0aW9uLWMxcWNlcmtoLmF1dGhlbnRpY2F0aW9uLmV1MTAuaGFuYS5vbmRlbWFuZC5jb20vb2F1dGgvdG9rZW4=
  token_service_url_pattern:
    aHR0cHM6Ly97dGVuYW50fS5hdXRoZW50aWNhdGlvbi5ldTEwLmhhbmEub25kZW1hbmQuY29tL29hdXRoL3Rva2Vu
  token_service_url_pattern_tenant_key: c3ViYWNjb3VudF9zdWJkb21haW4=
  type: Y29ubmVjdGl2aXR5
  xsappname:
    Y2xvbmU0NjNjYThjZDM3OGY0NDNlODAzNDg0NWNhNzlhOGY4ZSFiMjI2NDk1fGNvbm5lY3Rpdml0eSFiMTc=
  